### ISSUE TITLE
Error on the /setup process

### ISSUE THREAD

**Issue by jovenbarola** [PAWECOGmbH/saaster#310]
My development pc:
- Windows 10
- Lucee 5.3.7.45-RC (same with other Lucee 5.3.x)
- MySQL (bundled XAMPP 5.x)

I was caught having this error, when I tried to setup on my local-machine it stop from step3.cfm
![image](https://user-images.githubusercontent.com/129955/216742425-1c64beec-c5de-41d4-b786-dfa2fab75b36.png)

I have checked and traced the error from the source code, and found it on this line
![image](https://user-images.githubusercontent.com/129955/216742476-79c053e2-1420-4936-9e16-cff6d3b98060.png)

So i did a quick fix by deleting the first line.. and the issue is gone,
![image](https://user-images.githubusercontent.com/129955/216742601-7153fbae-b6cd-44c4-b565-9b3c8f701827.png)

I think this was related on how the MySQL rules, is setup on my end.. So I was thinking maybe i can share or ask if this still relevant, and maybe you can remove it from your next build? 

I understand that the current design was more into docker environment kind of setup, but i think some user still using the other old kind of setup :)

**Comment by rbuechler** [comment]
I believe the problem you are experiencing is because you have not enabled Multiple Queries in the Lucee Datasource.

![image](https://user-images.githubusercontent.com/97615157/217167613-1e4c2254-8e4c-4774-8fd5-e1affa08f865.png)

**Comment by jovenbarola** [comment]
Ow thats right, this now worked for me

**Comment by jovenbarola** [comment]
Just reference to other people that will experience the same
